# Generated by Django 4.2 on 2023-05-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options_alter_dish_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category-images/', verbose_name='Фотография'),
        ),
    ]
