# Generated by Django 4.2 on 2023-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_stoped',
            field=models.BooleanField(default=False, verbose_name='Заблокировано'),
        ),
    ]
