# Generated by Django 4.2 on 2023-06-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAdmin',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.profile')),
            ],
            bases=('catalog.profile',),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиля'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
